name: callpanion_elderly
description: CallPanion Elderly App with native call experience
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_callkit_incoming: ^3.0.0
  firebase_messaging: ^16.0.1
  firebase_core: ^4.1.0
  uuid: ^4.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2

  permission_handler: ^12.0.1
  connectivity_plus: ^6.0.5
  wakelock_plus: ^1.2.8

  # ElevenLabs dependencies
  dio: ^5.3.2
  envied: ^1.3.0

  # WebRTC dependencies - ElevenLabs SDK sudah include WebRTC
  # flutter_webrtc: ^0.9.48 # Tidak diperlukan, ElevenLabs SDK sudah include

  # Audio dependencies
  just_audio: ^0.9.36
  audio_session: ^0.1.16

  # Chat dependencies
  supabase_flutter: ^2.10.2
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1
  
  # Font dependencies
  google_fonts: ^6.3.2

  # Gallery/Memory dependencies
  flutter_layout_grid: ^2.0.8
  gal: ^2.3.0
  photo_view: ^0.15.0
  path_provider: ^2.1.5

  # QR Code Scanner
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/Callpanion_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/Callpanion_icon.png"
