-- Add new consent types to support comprehensive GDPR compliance
ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'HEALTH_MONITORING';
ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'EMERGENCY_CONTACT';
ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'SERVICE_IMPROVEMENT';
ALTER TYPE consent_type ADD VALUE IF NOT EXISTS 'PRIVACY_POLICY';