-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZnMiP6R28ynJ2W3s
pLpjQyAYfBdMwY3cxwnXPmBwc7WgCgYIKoZIzj0DAQehRANCAAQbr+uobW/oXso7
vRjmWhAOQHaZosKz/XICzU/JsMVNVIa+Eas9zpDn4opcMc/BX9AaMrhl6+d79AKC
x3SKWeQG
-----END PRIVATE KEY-----