project_id = "umjtepmdwfyfhdzbkyli"

[functions.ai-companion-chat]
verify_jwt = true

[functions.ai-conversation-analysis]
verify_jwt = true

[functions.ai-realtime-call]
verify_jwt = false

[functions.api-middleware]
verify_jwt = true

[functions.check-email-exists]
verify_jwt = false

[functions.check-scheduled-calls]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.checkMissedCalls]
verify_jwt = true

[functions.cleanup-sessions]
verify_jwt = false

[functions.confirm-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.device-heartbeat]
verify_jwt = false

[functions.eleven-proxy]
verify_jwt = false

[functions.elevenlabs-call]
verify_jwt = true

[functions.elevenlabs-webhook]
verify_jwt = false

[functions.elevenlabs-webrtc-call]
verify_jwt = true

[functions.escalate-emergency]
verify_jwt = true

[functions.get-family-messages]
verify_jwt = true

[functions.get-stripe-customer-data]
verify_jwt = true

[functions.get-wellbeing-trends]
verify_jwt = true

[functions.getRtcToken]
verify_jwt = true

[functions.hubspot-sync]
verify_jwt = true

[functions.initiateWellbeingCall]
verify_jwt = true

[functions.invites]
verify_jwt = true

[functions.leads-submit]
verify_jwt = false

[functions.log-wellbeing]
verify_jwt = true

[functions.migrate-audio-data]
verify_jwt = true

[functions.monitor-call-sessions]
verify_jwt = false

[functions.notify-family]
verify_jwt = true

[functions.pair-claim]
verify_jwt = false

[functions.pair-init]
verify_jwt = true

[functions.placeCall]
verify_jwt = true

[functions.poll-batch-status]
verify_jwt = true

[functions.process-alert-rules]
verify_jwt = true

[functions.record-mood]
verify_jwt = true

[functions.register-fcm-token]
verify_jwt = false

[functions.schedulerDailyCalls]
verify_jwt = false

[functions.schedulerInAppCalls]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = true

[functions.send-invite-email-rl]
verify_jwt = true

[functions.send-apns-voip-notification]
verify_jwt = true

[functions.send-fcm-notification]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.sendFamilyAlert]
verify_jwt = true

[functions.snoozeCall]
verify_jwt = true

[functions.submit-content-report]
verify_jwt = true

[functions.support-create-ticket]
verify_jwt = true

[functions.support-dispatch]
verify_jwt = true

[functions.test-email]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.unsubscribe]
verify_jwt = false

[functions.updateCallStatus]
verify_jwt = true

[functions.upload-media]
verify_jwt = true

[functions.voice-end]
verify_jwt = true

[functions.voice-start]
verify_jwt = true

[functions.waitlist-signup]
verify_jwt = false

[functions.elevenlabs-device-call]
verify_jwt = false

[functions.update-device-call-status]
verify_jwt = false